webpack require animate.js fail
use webpack require animate.js fail.  chrome console 'Uncaught Error: Cannot find module "islider"'.
It should islider.js but not islider.